import { ClickInField } from './Stateful/ClickInField';

export const StructuralComponent = ({ typeField, setTypeField, arr, setArr }) => {
  return (
    <>
      <ClickInField
        typeField={typeField}
        setTypeField={setTypeField}
        arr={arr}
        setArr={setArr}
        dataIndex={1}
      />
      <ClickInField
        typeField={typeField}
        setTypeField={setTypeField}
        arr={arr}
        setArr={setArr}
        dataIndex={2}
      />
      <ClickInField
        typeField={typeField}
        setTypeField={setTypeField}
        arr={arr}
        setArr={setArr}
        dataIndex={3}
      />
      <ClickInField
        typeField={typeField}
        setTypeField={setTypeField}
        arr={arr}
        setArr={setArr}
        dataIndex={4}
      />
      <ClickInField
        typeField={typeField}
        setTypeField={setTypeField}
        arr={arr}
        setArr={setArr}
        dataIndex={5}
      />
      <ClickInField
        typeField={typeField}
        setTypeField={setTypeField}
        arr={arr}
        setArr={setArr}
        dataIndex={6}
      />
      <ClickInField
        typeField={typeField}
        setTypeField={setTypeField}
        arr={arr}
        setArr={setArr}
        dataIndex={7}
      />
      <ClickInField
        typeField={typeField}
        setTypeField={setTypeField}
        arr={arr}
        setArr={setArr}
        dataIndex={8}
      />
      <ClickInField
        typeField={typeField}
        setTypeField={setTypeField}
        arr={arr}
        setArr={setArr}
        dataIndex={9}
      />
    </>
  );
};
